### ISSUE TITLE
about the number of epochs

### ISSUE THREAD

**Issue by QueenZK520** [XiaofeiWang2018/DR#1]
您好，请问在第一阶段训练中，epoch数真的是30000吗？

**Comment by XiaofeiWang2018** [comment]
Thanks for your attention. A good question. In fact, you can train as many epoches as you wish till the model converges to the preferred performance. So, definitely 30000 is an option, but not mandatory.

**Comment by XiaofeiWang2018** [comment]
Thanks for your attention. A good question. In fact, you can train as many epoches as you wish till the model converges to the preferred performance. So, definitely 30000 is an option, but not mandatory.

**Comment by XiaofeiWang2018** [comment]
Thanks for your attention. A good question. In fact, you can train as many epoches as you wish till the model converges to the preferred performance. So, definitely 30000 is an option, but not mandatory.

**Comment by QueenZK520** [comment]
I also want to know have you done any preprocessing for original images in DDR.  I see that you load data from the folder named _img_after2_.

**Comment by QueenZK520** [comment]
I find that I get very low IOU in each lesion, especially in MA. 
May you share with me the value of IOU or DICE you get with your method.

**Comment by XiaofeiWang2018** [comment]
As for the preprocessing, certainly, proper preprocessing, e.g., black side cropping and illumination balance, is common and necessary for fundus image processing.  As for the IoU, I haven't test for it, you can just refer to the paper that estblished the DDR. BTW, I think one possible reason that causes the low IoU may be the improper process of the GT maps of DDR, which I remember are grayscaled but not binarized. In fact, I am now out of office for some tests these weeks and am quite busy with my phd application and graduation recently.

**Comment by QueenZK520** [comment]
Thank you very much! You are my idol! Thanks again.
